CREATE TABLE [dbo].[Tbl_WWS_Sample] (
    [RLKDNR] NUMERIC (7)     NOT NULL,
    [KDNAM]  VARCHAR (25)    NOT NULL,
    [KDNAM2] VARCHAR (25)    NOT NULL,
    [KDSTR]  VARCHAR (25)    NOT NULL,
    [KDPLZ]  DECIMAL (5)     NOT NULL,
    [KDORT]  VARCHAR (25)    NOT NULL,
    [RLRENR] DECIMAL (7)     NOT NULL,
    [RLDAVS] NUMERIC (8)     NOT NULL,
    [RLREDA] NUMERIC (8)     NOT NULL,
    [RLDANF] NUMERIC (8)     NOT NULL,
    [RLBETR] DECIMAL (13, 2) NOT NULL,
    [RLIKRN] DECIMAL (7)     NOT NULL,
    [RLVBNR] VARCHAR (7)     NOT NULL,
    [RLAD01] DECIMAL (7)     NOT NULL,
    [KDTXP2] VARCHAR (3)     NOT NULL
);

